### ISSUE TITLE
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class run.RunConfigurationFactory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: gdscript]

### ISSUE THREAD

**Issue by ulebok** [exigow/intellij-gdscript#126] opened 2022-05-23 10:42 UTC
Plugin version: ```0.32.0```
IDE version: ```PC-221.5591.52```
Exception: ```com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class run.RunConfigurationFactory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: gdscript]```
Stacktrace:
```text
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class run.RunConfigurationFactory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: gdscript]

```

**Comment by odisseus** [comment] 2023-07-21 12:58
This seems to be a duplicate of #84, which has been fixed in version 0.32.4.

**Closed** 2023-07-23 11:46 UTC
